name: Test Repo

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7 - 3.9'
          architecture: x64
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest
      - name: Test repo
        run: python -m pytest
